[build]
    publish = "public/"

[functions]
    directory = "functions"

[[redirects]]
    from = "/cors/score-saber/*"
    to = "https://scoresaber.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = '/build/*'
    to = '/build/:splat'
    status = 200

[[redirects]]
    from = '/assets/*'
    to = '/assets/:splat'
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true